#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: image_gallery_development
  host: localhost
  username: root
  password: root

development:
  <<: *default
  database: image_gallery_development

test:
  <<: *default
  database: image_gallery_test

production:
  <<: *default
  database: image_gallery_production
  username: image_gallery
  password: <%= ENV["IMAGE_GALLERY_DATABASE_PASSWORD"] %>
